---
- name: install repmgr
  apt: name={{ item }} state=present
  with_items:
  - repmgr
  - postgresql-{{ postgresql_version }}-repmgr
  register: repmgr_installed

- name: create repmgr conf dir
  file:
    recurse: yes
    path: "{{ repmgr_conf_dir }}"
    state: directory

- name: Stop repmgrd service
  service: name=repmgrd state=stopped

- name: create repmgr conf
  template:
    src: repmgr.conf.j2
    dest: "{{ repmgr_conf_dir }}/{{ repmgr_conf_file }}"
  register: repmgr_conf
  notify: restart repmgrd

- name: create repmgr conf
  template:
    src: repmgrd.j2
    dest: "/etc/default/repmgrd"
  notify: restart repmgrd

- name: register with repmgr
  shell: "repmgr -f {{ repmgr_conf_dir }}/{{ repmgr_conf_file }} --verbose master register"
  when: repmgr_conf.changed and repmgr_installed.changed and repmgr_is_master|bool

- include: standby-post-tasks.yml
  when: (repmgr_installed.changed and not repmgr_is_master|bool) or repmgr_reinit_slave|bool

- name: Start repmgrd service
  service: name=repmgrd state=started
